export const listNotices = [
  {
    title: 'OMS destaca que vacina contra HPV é segura e indispensável',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/04/oms-destaca-que-vacina-contra-hpv-e-segura-e-indispensavel.ghtml',
    like: 0,
    dislike: 0,
    state: 'MG',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Frio e calor extremos podem causar queimaduras, congelamentos e outros problemas de saúde',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/04/conselho-federal-de-medicina-permite-que-medicos-facam-consultas-e-cirurgias-remotas-no-brasil.ghtml',
    like: 0,
    dislike: 0,
    state: 'SP',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'OMS destaca que vacina contra HPV é segura e indispensável',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/04/oms-destaca-que-vacina-contra-hpv-e-segura-e-indispensavel.ghtml',
    like: 0,
    dislike: 0,
    state: 'MG',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'OMS destaca que vacina contra HPV é segura e indispensável',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/04/oms-destaca-que-vacina-contra-hpv-e-segura-e-indispensavel.ghtml',
    like: 0,
    dislike: 0,
    state: 'MG',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'OMS destaca que vacina contra HPV é segura e indispensável',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/04/oms-destaca-que-vacina-contra-hpv-e-segura-e-indispensavel.ghtml',
    like: 0,
    dislike: 0,
    state: 'MG',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'OMS destaca que vacina contra HPV é segura e indispensável',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/04/oms-destaca-que-vacina-contra-hpv-e-segura-e-indispensavel.ghtml',
    like: 0,
    dislike: 0,
    state: 'MG',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'OMS destaca que vacina contra HPV é segura e indispensável',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/04/oms-destaca-que-vacina-contra-hpv-e-segura-e-indispensavel.ghtml',
    like: 0,
    dislike: 0,
    state: 'MG',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Frio e calor extremos podem causar queimaduras, congelamentos e outros problemas de saúde',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/04/conselho-federal-de-medicina-permite-que-medicos-facam-consultas-e-cirurgias-remotas-no-brasil.ghtml',
    like: 0,
    dislike: 0,
    state: 'SP',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Frio e calor extremos podem causar queimaduras, congelamentos e outros problemas de saúde',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/04/conselho-federal-de-medicina-permite-que-medicos-facam-consultas-e-cirurgias-remotas-no-brasil.ghtml',
    like: 0,
    dislike: 0,
    state: 'SP',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Frio e calor extremos podem causar queimaduras, congelamentos e outros problemas de saúde',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/04/conselho-federal-de-medicina-permite-que-medicos-facam-consultas-e-cirurgias-remotas-no-brasil.ghtml',
    like: 0,
    dislike: 0,
    state: 'SP',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Frio e calor extremos podem causar queimaduras, congelamentos e outros problemas de saúde',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/04/conselho-federal-de-medicina-permite-que-medicos-facam-consultas-e-cirurgias-remotas-no-brasil.ghtml',
    like: 0,
    dislike: 0,
    state: 'SP',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Frio e calor extremos podem causar queimaduras, congelamentos e outros problemas de saúde',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/04/conselho-federal-de-medicina-permite-que-medicos-facam-consultas-e-cirurgias-remotas-no-brasil.ghtml',
    like: 0,
    dislike: 0,
    state: 'SP',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Frio e calor extremos podem causar queimaduras, congelamentos e outros problemas de saúde',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/04/conselho-federal-de-medicina-permite-que-medicos-facam-consultas-e-cirurgias-remotas-no-brasil.ghtml',
    like: 0,
    dislike: 0,
    state: 'SP',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Envelhecimento saudável: entenda como a ciência pode dobrar expectativa de vida',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/02/envelhecimento-saudavel-entenda-como-a-ciencia-pode-dobrar-expectativa-de-vida.ghtml',
    like: 0,
    dislike: 0,
    state: 'RS',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Envelhecimento saudável: entenda como a ciência pode dobrar expectativa de vida',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/02/envelhecimento-saudavel-entenda-como-a-ciencia-pode-dobrar-expectativa-de-vida.ghtml',
    like: 0,
    dislike: 0,
    state: 'RS',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Envelhecimento saudável: entenda como a ciência pode dobrar expectativa de vida',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/02/envelhecimento-saudavel-entenda-como-a-ciencia-pode-dobrar-expectativa-de-vida.ghtml',
    like: 0,
    dislike: 0,
    state: 'RS',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Envelhecimento saudável: entenda como a ciência pode dobrar expectativa de vida',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/02/envelhecimento-saudavel-entenda-como-a-ciencia-pode-dobrar-expectativa-de-vida.ghtml',
    like: 0,
    dislike: 0,
    state: 'RS',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Envelhecimento saudável: entenda como a ciência pode dobrar expectativa de vida',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/02/envelhecimento-saudavel-entenda-como-a-ciencia-pode-dobrar-expectativa-de-vida.ghtml',
    like: 0,
    dislike: 0,
    state: 'RS',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Envelhecimento saudável: entenda como a ciência pode dobrar expectativa de vida',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/02/envelhecimento-saudavel-entenda-como-a-ciencia-pode-dobrar-expectativa-de-vida.ghtml',
    like: 0,
    dislike: 0,
    state: 'RS',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Envelhecimento saudável: entenda como a ciência pode dobrar expectativa de vida',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/02/envelhecimento-saudavel-entenda-como-a-ciencia-pode-dobrar-expectativa-de-vida.ghtml',
    like: 0,
    dislike: 0,
    state: 'RS',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Envelhecimento saudável: entenda como a ciência pode dobrar expectativa de vida',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/02/envelhecimento-saudavel-entenda-como-a-ciencia-pode-dobrar-expectativa-de-vida.ghtml',
    like: 0,
    dislike: 0,
    state: 'RS',
    date: '04/02/2019',
    site: 'G1',
  },
  {
    title: 'Envelhecimento saudável: entenda como a ciência pode dobrar expectativa de vida',
    url: 'https://g1.globo.com/ciencia-e-saude/noticia/2019/02/02/envelhecimento-saudavel-entenda-como-a-ciencia-pode-dobrar-expectativa-de-vida.ghtml',
    like: 0,
    dislike: 0,
    state: 'RS',
    date: '04/02/2019',
    site: 'G1',
  },
]